create table Address (id integer not null, version integer, hausnummer varchar(255), ort varchar(255), plz varchar(255), strasse varchar(255), primary key (id))
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
create table Person (id integer not null, version integer, geburtsdatum varchar(255), nachname varchar(255), vorname varchar(255), ADDRESS_ID integer, primary key (id))
create table Vehicle (VEHICLE_TYPE varchar(31) not null, id integer not null, version integer, description varchar(255), type integer, modell varchar(255), OWNER_ID integer, primary key (id))
alter table Person add constraint FK7hs06ply1oy9a1735sii1iced foreign key (ADDRESS_ID) references Address (id)
alter table Vehicle add constraint FKird0jsckjobdsnjeof5686hog foreign key (OWNER_ID) references Person (id)
